# Generated by Django 6.0.2 on 2026-02-26 06:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
        ('reviews', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('property', 'guest')},
        ),
    ]
